CREATE TABLE atelier_point5min (
  id int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID unique',
  date date NOT NULL COMMENT 'Date du point 5min',
  type_item varchar(20) NOT NULL COMMENT 'Rubrique du point 5min sécurité,qualité,aléas',
  temps int(11) DEFAULT NULL COMMENT 'Temps perdu (minutes)',
  fk_article int(11) DEFAULT NULL COMMENT 'FK vers prod_article',
  numero varchar(50) DEFAULT NULL COMMENT 'Numéro produit',
  num_rotor varchar(50) DEFAULT NULL COMMENT 'Numéro du rotor',
  num_stator varchar(50) DEFAULT NULL COMMENT 'Numéro du stator',
  num_palier varchar(50) DEFAULT NULL COMMENT 'Numéro du palier',
  origine_alea_type enum('opérateur','fournisseur','client','machine','autre') NOT NULL DEFAULT 'autre' COMMENT 'Type d''origine de l''aléa',
  origine_alea_id int(11) DEFAULT NULL COMMENT 'ID de l''origine selon le type',
  origine_alea_label varchar(100) DEFAULT NULL COMMENT 'Nom libre si origine = autre',
  operation varchar(100) DEFAULT NULL COMMENT 'Opération précise du process',
  type_alea varchar(50) DEFAULT NULL COMMENT 'Catégorie d''aléa',
  alea varchar(50) DEFAULT NULL COMMENT 'Intitulé court de l''aléa',
  commentaire text DEFAULT NULL COMMENT 'Infos complémentaires',
  action text DEFAULT NULL COMMENT 'Plan d''action',
  fnc varchar(50) DEFAULT NULL COMMENT 'N° de FNC',
  zone varchar(50) DEFAULT NULL COMMENT 'Zone/atelier',
  centre_charge varchar(50) DEFAULT NULL COMMENT 'Centre de charge',
  semaine varchar(8) GENERATED ALWAYS AS (concat(left(yearweek(date,3),4),'-',right(yearweek(date,3),2))) VIRTUAL COMMENT 'Numéro de semaine ISO',
  PRIMARY KEY (id),
  KEY fk_atelier_point5min_article (fk_article),
  CONSTRAINT fk_atelier_point5min_article FOREIGN KEY (fk_article) REFERENCES prod_articles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='Table centrale pour la collecte digitalisée du point 5min (atelier)';